name: First workflow
#manunaly start
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    #each step starts with - (dash) 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
      # if we want to run multiple sripts use | 
        run: |
          echo "Done - bye!"
          echo "Bye again!"

